#!/usr/bin/python3
"""This module defines a class MyList that inherits from list."""


class MyList(list):
    """A list subclass with a print_sorted method."""

    def print_sorted(self):
        """Print the list in ascending order."""
        print(sorted(self))

